export const ROLE_PAGE_LOADED = 'ROLE_PAGE_LOADED';
export const ROLE_PAGE_UNLOADED = 'ROLE_PAGE_UNLOADED';

export const ROLE_VIEW_PAGE_LOADED = 'ROLE_VIEW_PAGE_LOADED';
export const ROLE_VIEW_PAGE_UNLOADED = 'ROLE_VIEW_PAGE_UNLOADED';

export const ROLE_CREATE = 'ROLE_CREATE';
export const ROLE_UPDATE = 'ROLE_UPDATE';

export const ROLE_EDITOR_PAGE_LOADED = 'ROLE_EDITOR_PAGE_LOADED';
export const ROLE_EDITOR_PAGE_UNLOADED = 'ROLE_EDITOR_PAGE_UNLOADED';
export const ROLE_DELETE = 'ROLE_DELETE';