export const USER_PAGE_LOADED = 'USER_PAGE_LOADED';
export const USER_PAGE_UNLOADED = 'USER_PAGE_UNLOADED';
export const USER_PAGE_REQUESTED = 'USER_PAGE_REQUESTED';

export const USER_VIEW_PAGE_LOADED = 'USER_VIEW_PAGE_LOADED';
export const USER_VIEW_PAGE_UNLOADED = 'USER_VIEW_PAGE_UNLOADED';

export const USER_CREATE = 'USER_CREATE';
export const USER_UPDATE = 'USER_UPDATE';

export const USER_EDITOR_PAGE_LOADED = 'USER_EDITOR_PAGE_LOADED';
export const USER_EDITOR_PAGE_UNLOADED = 'USER_EDITOR_PAGE_UNLOADED';
export const USER_DELETE = 'USER_DELETE';