export const BACKEND_LOGIN = 'BACKEND_LOGIN';
export const BACKEND_LOGOUT = 'BACKEND_LOGOUT';
export const BACKEND_REGISTER = 'BACKEND_REGISTER';
export const BACKEND_AUTH_USER = 'BACKEND_AUTH_USER';
export const BACKEND_AUTH_ERROR = 'BACKEND_AUTH_ERROR';
export const BACKEND_LOGIN_PAGE_UNLOADED = 'BACKEND_LOGIN_PAGE_UNLOADED';
export const BACKEND_REGISTER_PAGE_UNLOADED = 'BACKEND_LOGIN_PAGE_UNLOADED';
export const BACKEND_REGISTER_PAGE_LOADED = 'BACKEND_REGISTER_PAGE_LOADED';