export const PERMISSION_LIST_PAGE_LOADED = 'PERMISSION_LIST_PAGE_LOADED';
export const PERMISSION_LIST_PAGE_UNLOADED = 'PERMISSION_LIST_PAGE_UNLOADED';
export const PERMISSION_LIST_PAGE_REQUESTED = 'PERMISSION_LIST_PAGE_REQUESTED';

export const PERMISSION_VIEW_PAGE_LOADED = 'PERMISSION_VIEW_PAGE_LOADED';
export const PERMISSION_VIEW_PAGE_UNLOADED = 'PERMISSION_VIEW_PAGE_UNLOADED';

export const PERMISSION_CREATE = 'PERMISSION_CREATE';
export const PERMISSION_UPDATE = 'PERMISSION_UPDATE';

export const PERMISSION_FORM_PAGE_LOADED = 'PERMISSION_FORM_PAGE_LOADED';
export const PERMISSION_FORM_PAGE_UNLOADED = 'PERMISSION_FORM_PAGE_UNLOADED';

export const PERMISSION_DELETE = 'PERMISSION_DELETE';
